"""Correção de tabela

Revision ID: 831573a83b56
Revises: 03ea457672f3
Create Date: 2025-09-28 21:43:12.293842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831573a83b56'
down_revision: Union[str, Sequence[str], None] = '03ea457672f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativo', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
